version: '3.8'

x-environment: &CLIENTBOTTLE_ENV
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  MODE: ${MODE:-DEV}
  VERSION: ${VERSION:-0.0.1}

x-clientbottle-service: &CLIENTBOTTLE_SERVICE
  build:
    context: .
    args:
      VERSION: ${VERSION}
  restart: always
  depends_on:
    - postgres
  volumes:
    - ./server:/app/server
    - ./alembic:/app/alembic
    - ./alembic.ini:/app/alembic.ini
    - ./exec:/app/exec
    - ./.tmp/volumes/tmp:/app/.tmp
    # - type: bind
    #   source: ${PWD}/.env
    #   target: /app/.env
  networks:
    - internal

services:
  postgres:
    ports:
      - "5531:5432"
    image: postgres:16.1
    restart: always
    volumes:
      - ./.tmp/volumes/pg:/var/lib/postgresql/data
    environment: *CLIENTBOTTLE_ENV
    networks:
      - internal

  api:
    ports:
      - "7071:7071"
    image: thbraum/clientbottle:${VERSION}
    <<: *CLIENTBOTTLE_SERVICE
    environment:
      <<: *CLIENTBOTTLE_ENV
networks:
  internal:
    # external: true